export const data = [
  {
    id: 1,
    siteName: "Netflix",
    siteUrl: "www.netflix.com",
    email: "userNetflix@gmail.com",
    visitedDate: "14/9/2021",
    visitedTime: "12:00:00 PM",
  },
  {
    id: 2,
    siteName: "Amazon",
    siteUrl: "www.amazon.com",
    email: "userAmazon@gmail.com",
    visitedDate: "14/9/2021",
    visitedTime: "12:00:00 PM",
  },
  {
    id: 3,
    siteName: "Myntra",
    siteUrl: "www.Myntra.com",
    email: "userMyntra@gmail.com",
    visitedDate: "14/9/2021",
    visitedTime: "12:00:00 PM",
  },
  {
    id: 4,
    siteName: "Ajio",
    siteUrl: "www.Ajio.com",
    email: "userAjio@gmail.com",
    visitedDate: "14/9/2021",
    visitedTime: "12:00:00 PM",
  },
  {
    id: 5,
    siteName: "Youtube",
    siteUrl: "www.Youtube.com",
    email: "userYoutube@gmail.com",
    visitedDate: "14/9/2021",
    visitedTime: "12:00:00 PM",
  },
];
